services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: subs
      POSTGRES_USER: subs
      POSTGRES_PASSWORD: subs
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SUBS_POSTGRES_DSN: postgres://subs:subs@db:5432/subs?sslmode=disable
      SUBS_LOG_LEVEL: info
      SUBS_HTTP_ADDRESS: :8080
    ports:
      - "8080:8080"
volumes:
  dbdata: {}



